### PR TITLE
Makes the data directory configurable

### PR DESCRIPTION
**Pull request by Silv3rcircl3**

### CODE REVIEW

**Comment by JohannesHoppe** [comment]
Many thanks! I will upload a new nuget package as soon as I have some free time!

**Comment by Silv3rcircl3** [comment]
Cool, looking forward for the new version.

**Comment by Silv3rcircl3** [comment]
Can I help you out with something for the new version? I need the future for a project and would like to replace the local dll with the new nuget package ;)

**Comment by JohannesHoppe** [comment]
Done. Sorry for the delay. My current project is not using MongoDB so the nuget package is a bit orphaned. Would you be interested to get co-owner status of the nuget package as well as read/write access to the repository?

**Comment by Silv3rcircl3** [comment]
Great, tanks!
I see no reason to say no ;-) 
But I only have provided PR's to other projects, so I don't know what I have to do as a co-owner. 
Or with other words, could you explain me for what you "need" me as a co-owner or what your plans are?

**Comment by JohannesHoppe** [comment]
Nothing special. I just don’t want to be the only guy maintaining the package! You are now a colaborator on github.

You might want to add missing features? It won’t work on mono, too. The mongodb binaries are also very old… feel free to change whatever you want – or not! ;-)

What is you nuget.org username?

**Comment by Silv3rcircl3** [comment]
Alright :)
Unfortunately I never used mono so I can't provide any help here, but if I need something else, I will implement it.

My nuget username is also Silv3rcircl3

**Comment by JohannesHoppe** [comment]
:+1: Welcome to the club! :-)

**Comment by Silv3rcircl3** [comment]
Danke :)
Hätte ich mal eher auf deinen Nick geklickt, hätten wir das ganze auch in Deutsch besprechen können ^^

**Comment by JohannesHoppe** [comment]
Ist mir auch schon aufgefallen! ^_^

**Pull request merged**
