### PR TITLE
adding message to help trouble shoot working directory issues

### PR DESCRIPTION
**Pull request by G3N7**
I am trying to get Mongo2Go working in travis-ci and could use to know where the executing test's context is that is giving me this exception.

### CODE REVIEW

**Comment by JohannesHoppe** [comment]
I like that idea. But I wouldn't use Interpolated Strings (C# 6) here, my goal is to keep it compatible with older versions of Visual Studio, too.

**Comment by JohannesHoppe** [comment]
Different topic: you wrote **tracis-ci**.

I don't think that your plan will work that easily.
Travis-CI is a Linux environment and uses mono. So the C# part should work, but it won't be able to start the executables, since they are binaries for Windows.

However it might work to retrieve the right executables using `apt-get` and/or [the ready-to-use database setup](https://docs.travis-ci.com/user/database-setup/#MongoDB) of travis-ci:

    services:
      - mongodb

In both cases the search for the executables needs to be extended.
Something like:
`public static MongoDbRunner Start(string dataDirectory = MongoDbDefaults.DataDirectory, string findFolderStartPath = null)`

See https://github.com/JohannesHoppe/Mongo2Go/blob/master/src/Mongo2Go/MongoDbRunner.cs#L34 / https://github.com/JohannesHoppe/Mongo2Go/blob/master/src/Mongo2Go/MongoDbRunner.cs#L51

**Comment by G3N7** [comment]
Interesting ok sounds good, I will try those routes.  Thank you for your help!

**Comment by G3N7** [comment]
OK, I moved to `string.format`.  Thank you for your recommendation, I have moved to using the mongodb service in travis as suggested and its working like a charm.

**Comment by JohannesHoppe** [comment]
Do you mind to send another pull request + readme update about your work to enable Mongo2Go on Travis-CI? :-)

**Comment by G3N7** [comment]
So I actually alternate between if I use Mongo2Go or an alternate temporary DB.

I added a few comments to this commit to explain what I am doing.
https://github.com/G3N7/MonJobs/commit/4e66241440a9604f4889a3421447122703e3b0e1

**Comment by G3N7** [comment]
Take a look and let me know if you think others would benefit from this approach, the pattern I and colleges have settled on injects the IMongoDatabase.  Take a look at https://github.com/G3N7/MonJobs/blob/master/MonJobs.Tests/MongoJobQueryServiceTests.cs for a few examples of how the tests end up looking.

**Comment by JohannesHoppe** [comment]
This looks like serious tested and well done-work! :+1: :smile: 

What about a pull request to the Readme.md? You could write that it's technically possible to run this on travis and that people should refer to MonJobs to figure out how it works!

There are other people that are trying the same right now:
see https://github.com/JohannesHoppe/Mongo2Go/issues/9

**Comment by G3N7** [comment]
That sounds great, thanks for taking a look.  I will send you a pull request sometime next week once my family has left from visiting.

**Pull request merged**
