### PR TITLE
Refreshed MongoDB version, bumped package version

### PR DESCRIPTION
**Pull request by onyxmaster**

### CODE REVIEW

**Comment by JohannesHoppe** [comment]
Thanks! I will check & merge tomorrow!

**Comment by JohannesHoppe** [comment]
Available on nuget:
https://www.nuget.org/packages/Mongo2Go/0.1.7

**Comment by onyxmaster** [comment]
Unfortunately, I forgot to refresh the AssemblyVersion and AssemblyFileVersion. Could you fix it (going to 0.1.8) or should I make a new PR?

**Comment by JohannesHoppe** [comment]
I will fix that and replace the package.

**Comment by JohannesHoppe** [comment]
This is now v0.1.8
https://www.nuget.org/packages/Mongo2Go/0.1.8

Cheers! :beer:

**Comment by onyxmaster** [comment]
Great news, thank you!

**Pull request merged**
