### PR TITLE
add random folder option

### PR DESCRIPTION
**Pull request by cottsak**
adding option to use a different folder each time to absolutely ensure test isolation in debugging/dev scenarios

### CODE REVIEW

**Comment by JohannesHoppe** [comment]
see `_dataDirectoryWithPort ``. it already uses everythime a different directory. can you describe the reason for the change?

**Comment by cottsak** [comment]
The folder is only unique to the port, which is not enough. When I'm building out my test (prior to it passing and failing all the way to the end of the `using`block which `Dispose()`s the runner), I run the test, in part, many many times. On these runs, the in-memory mongo process finds the same available port, meaning it's the same folder on my disk every time. Then, as a result of https://github.com/JohannesHoppe/Mongo2Go/issues/17 my data directory is not being cleaned up. So my workaround was to supply a random path (suffux) for each run and then i could be assured of a consistent test environment. This PR simply formalises that work-around.

**Comment by JohannesHoppe** [comment]
Okay. Makes sence. Then I suggest to remove the param and make `Guid`-based-directory the new default behavior. I was initially expecting that port-based-directory gives enough isolation. When done, I’m happily accept the commit.

**Comment by cottsak** [comment]
@JohannesHoppe Ok. Updated. Sorry about the whitespace.

**Comment by JohannesHoppe** [comment]
LGTM!

**Comment by cottsak** [comment]
Thanks. So when do we see a new package version?

**Comment by JohannesHoppe** [comment]
Any time. Do you need it urgently or can we wait for #17 and #19?

**Comment by cottsak** [comment]
I should show you how to set up a free AppVeyor account to continuously push to nuget. Provided the process works for the tests, you wouldn't have to do anything then.

**Comment by JohannesHoppe** [comment]
I guees it works similar to Travis-CI? Anyhow, I signed up there and already added Mongo2Go to the projects. What's next?

In a perfect world:
* master goes continuously to MyGet
* tagged commits go to Nuget

**Comment by cottsak** [comment]
@JohannesHoppe Yes, same product category as Travis.

You can take a look a http://www.hanselman.com/blog/AppVeyorAGoodContinuousIntegrationSystemIsAJoyToBehold.aspx if you like, but it's probably easier for you just to get in there are figure it out.

You essentially need to:

* Create a new project and connect it to your github repo
* On the *General* page, specify a *Build version format* and then turn on *AssemblyInfo patching* - I find this to be the easiest way.
* On the *Build* page you may need to *Package NuGet projects* and add `nuget restore` to the *Before build script* (CMD)
* On the *Deployment* page choose *NuGet* from the provider list and get your api key in there. You will also want to set *Deploy from branch* to `master` otherwise all PRs will have packages deployed too, which you don't want.
* Jump to the *Badges* page and copy the image link for your build status page and put it into your readme ([like this](https://raw.githubusercontent.com/cottsak/DevCookie/master/README.md)).
* Make a commit to include your AssemblyInfo changes after saving the above and watch the build trigger off and see what happens.

I may have forgot one or two small things, but pretty much that's it. The only tricky thing will be whether AppVeyor runs your integration tests because of the child process. Give it a go- it may 'just work'. Ping me if not and we can work through some things I've tried before for integration tests.

**Comment by JohannesHoppe** [comment]
Wow, that's very much work to setup everything.  :disappointed: 

Right now I click:
```
package_create.cmd
package_push.cmd
```

**Comment by cottsak** [comment]
@JohannesHoppe yeh but you have to push version number changes and click those scripts every time. Once this is done *once*, that's it!

I guess you just have to figure out how important your time is. 😛

**Comment by JohannesHoppe** [comment]
Time is short! :cry: 

If I would make you admin of my AppVeyor account, could you set up this for me/us?
I would be also fine to migrate Mongo2Go to github.com/Mongo2Go/Mongo2Go to make it more community-driven. What do you prefer?

**Comment by cottsak** [comment]
@JohannesHoppe I emailed you mate.

**Pull request merged**
