### PR TITLE
hide process windows

### PR DESCRIPTION
**Pull request by cottsak**
hide the process windows. there's nothing to see in them anyway. this really improves the dev workflow especially for continuous testing tools like NCrunch.

### CODE REVIEW

**Comment by JohannesHoppe** [comment]
I agree, the windows have no real advantage.

**Comment by cottsak** [comment]
I'd appreciate this change getting a new package built. This will improve my dev process immediately.

**Comment by JohannesHoppe** [comment]
Mongo2Go 1.0.0-beta3 is uploaded to the NuGet Galery!

**Comment by cottsak** [comment]
@JohannesHoppe Thanks mate! It's working well.

**Comment by JohannesHoppe** [comment]
:smile:

**Pull request merged**
